/*
 * Laserfiche Repository API
 * Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>eb72c77d640efc5f986310ccc43114fc25742dab_.20220610.1</p>
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.laserfiche.repository.api.clients.impl.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets OperationStatus
 */
@JsonAdapter(OperationStatus.Adapter.class)
public enum OperationStatus {
  NOTSTARTED("NotStarted"),
  INPROGRESS("InProgress"),
  COMPLETED("Completed"),
  FAILED("Failed"),
  CANCELLED("Cancelled");

  private String value;

  OperationStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OperationStatus fromValue(String input) {
    for (OperationStatus b : OperationStatus.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<OperationStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final OperationStatus enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public OperationStatus read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return OperationStatus.fromValue((String)(value));
    }
  }
}
