/*
 * Laserfiche Repository API
 * Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>eb72c77d640efc5f986310ccc43114fc25742dab_.20220610.1</p>
 *
 * OpenAPI spec version: 2-alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.laserfiche.repository.api.clients.impl.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PostEntryChildrenEntryType
 */
@JsonAdapter(PostEntryChildrenEntryType.Adapter.class)
public enum PostEntryChildrenEntryType {
  FOLDER("Folder"),
  SHORTCUT("Shortcut");

  private String value;

  PostEntryChildrenEntryType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PostEntryChildrenEntryType fromValue(String input) {
    for (PostEntryChildrenEntryType b : PostEntryChildrenEntryType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PostEntryChildrenEntryType> {
    @Override
    public void write(final JsonWriter jsonWriter, final PostEntryChildrenEntryType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public PostEntryChildrenEntryType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return PostEntryChildrenEntryType.fromValue((String)(value));
    }
  }
}
