/*
 * Laserfiche Repository API
 * Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>eb72c77d640efc5f986310ccc43114fc25742dab_.20220610.1</p>
 *
 * OpenAPI spec version: 2-alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.laserfiche.repository.api.clients.impl.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * SimpleImportRequest
 */

public class SimpleImportRequest {
  @SerializedName("name")
  private String name = null;

  @SerializedName("autoRename")
  private Boolean autoRename = null;

  @SerializedName("generateText")
  private Boolean generateText = false;

  @SerializedName("importAsElectronicDocument")
  private Boolean importAsElectronicDocument = false;

  @SerializedName("template")
  private String template = null;

  @SerializedName("metadata")
  private SimpleImportMetadata metadata = null;

  public SimpleImportRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SimpleImportRequest autoRename(Boolean autoRename) {
    this.autoRename = autoRename;
    return this;
  }

   /**
   * Get autoRename
   * @return autoRename
  **/
  @Schema(description = "")
  public Boolean isAutoRename() {
    return autoRename;
  }

  public void setAutoRename(Boolean autoRename) {
    this.autoRename = autoRename;
  }

  public SimpleImportRequest generateText(Boolean generateText) {
    this.generateText = generateText;
    return this;
  }

   /**
   * Get generateText
   * @return generateText
  **/
  @Schema(description = "")
  public Boolean isGenerateText() {
    return generateText;
  }

  public void setGenerateText(Boolean generateText) {
    this.generateText = generateText;
  }

  public SimpleImportRequest importAsElectronicDocument(Boolean importAsElectronicDocument) {
    this.importAsElectronicDocument = importAsElectronicDocument;
    return this;
  }

   /**
   * Get importAsElectronicDocument
   * @return importAsElectronicDocument
  **/
  @Schema(description = "")
  public Boolean isImportAsElectronicDocument() {
    return importAsElectronicDocument;
  }

  public void setImportAsElectronicDocument(Boolean importAsElectronicDocument) {
    this.importAsElectronicDocument = importAsElectronicDocument;
  }

  public SimpleImportRequest template(String template) {
    this.template = template;
    return this;
  }

   /**
   * The name of the template assigned to the entry.
   * @return template
  **/
  @Schema(description = "The name of the template assigned to the entry.")
  public String getTemplate() {
    return template;
  }

  public void setTemplate(String template) {
    this.template = template;
  }

  public SimpleImportRequest metadata(SimpleImportMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @Schema(description = "")
  public SimpleImportMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(SimpleImportMetadata metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimpleImportRequest simpleImportRequest = (SimpleImportRequest) o;
    return Objects.equals(this.name, simpleImportRequest.name) &&
        Objects.equals(this.autoRename, simpleImportRequest.autoRename) &&
        Objects.equals(this.generateText, simpleImportRequest.generateText) &&
        Objects.equals(this.importAsElectronicDocument, simpleImportRequest.importAsElectronicDocument) &&
        Objects.equals(this.template, simpleImportRequest.template) &&
        Objects.equals(this.metadata, simpleImportRequest.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, autoRename, generateText, importAsElectronicDocument, template, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimpleImportRequest {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    autoRename: ").append(toIndentedString(autoRename)).append("\n");
    sb.append("    generateText: ").append(toIndentedString(generateText)).append("\n");
    sb.append("    importAsElectronicDocument: ").append(toIndentedString(importAsElectronicDocument)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
