/*
 * Laserfiche Repository API
 * Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>eb72c77d640efc5f986310ccc43114fc25742dab_.20220610.1</p>
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.laserfiche.repository.api.clients.impl.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets WFieldType
 */
@JsonAdapter(WFieldType.Adapter.class)
public enum WFieldType {
  DATETIME("DateTime"),
  BLOB("Blob"),
  DATE("Date"),
  SHORTINTEGER("ShortInteger"),
  LONGINTEGER("LongInteger"),
  LIST("List"),
  NUMBER("Number"),
  STRING("String"),
  TIME("Time");

  private String value;

  WFieldType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WFieldType fromValue(String input) {
    for (WFieldType b : WFieldType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<WFieldType> {
    @Override
    public void write(final JsonWriter jsonWriter, final WFieldType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public WFieldType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return WFieldType.fromValue((String)(value));
    }
  }
}
