/*
 * Laserfiche Repository API
 * Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>eb72c77d640efc5f986310ccc43114fc25742dab_.20220610.1</p>
 *
 * OpenAPI spec version: 2-alpha
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.laserfiche.repository.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.laserfiche.repository.api.client.model.OperationErrorItem;
import com.laserfiche.repository.api.client.model.OperationStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * OperationProgress
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-06-21T09:31:30.649462900-04:00[America/New_York]")
public class OperationProgress {
  @SerializedName("operationToken")
  private String operationToken = null;

  @SerializedName("operationType")
  private String operationType = null;

  @SerializedName("percentComplete")
  private Integer percentComplete = null;

  @SerializedName("status")
  private OperationStatus status = null;

  @SerializedName("errors")
  private List<OperationErrorItem> errors = null;

  @SerializedName("redirectUri")
  private String redirectUri = null;

  public OperationProgress operationToken(String operationToken) {
    this.operationToken = operationToken;
    return this;
  }

   /**
   * Get operationToken
   * @return operationToken
  **/
  @Schema(description = "")
  public String getOperationToken() {
    return operationToken;
  }

  public void setOperationToken(String operationToken) {
    this.operationToken = operationToken;
  }

  public OperationProgress operationType(String operationType) {
    this.operationType = operationType;
    return this;
  }

   /**
   * Get operationType
   * @return operationType
  **/
  @Schema(description = "")
  public String getOperationType() {
    return operationType;
  }

  public void setOperationType(String operationType) {
    this.operationType = operationType;
  }

  public OperationProgress percentComplete(Integer percentComplete) {
    this.percentComplete = percentComplete;
    return this;
  }

   /**
   * Get percentComplete
   * @return percentComplete
  **/
  @Schema(description = "")
  public Integer getPercentComplete() {
    return percentComplete;
  }

  public void setPercentComplete(Integer percentComplete) {
    this.percentComplete = percentComplete;
  }

  public OperationProgress status(OperationStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public OperationStatus getStatus() {
    return status;
  }

  public void setStatus(OperationStatus status) {
    this.status = status;
  }

  public OperationProgress errors(List<OperationErrorItem> errors) {
    this.errors = errors;
    return this;
  }

  public OperationProgress addErrorsItem(OperationErrorItem errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<OperationErrorItem>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @Schema(description = "")
  public List<OperationErrorItem> getErrors() {
    return errors;
  }

  public void setErrors(List<OperationErrorItem> errors) {
    this.errors = errors;
  }

  public OperationProgress redirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
    return this;
  }

   /**
   * Get redirectUri
   * @return redirectUri
  **/
  @Schema(description = "")
  public String getRedirectUri() {
    return redirectUri;
  }

  public void setRedirectUri(String redirectUri) {
    this.redirectUri = redirectUri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationProgress operationProgress = (OperationProgress) o;
    return Objects.equals(this.operationToken, operationProgress.operationToken) &&
        Objects.equals(this.operationType, operationProgress.operationType) &&
        Objects.equals(this.percentComplete, operationProgress.percentComplete) &&
        Objects.equals(this.status, operationProgress.status) &&
        Objects.equals(this.errors, operationProgress.errors) &&
        Objects.equals(this.redirectUri, operationProgress.redirectUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operationToken, operationType, percentComplete, status, errors, redirectUri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationProgress {\n");
    
    sb.append("    operationToken: ").append(toIndentedString(operationToken)).append("\n");
    sb.append("    operationType: ").append(toIndentedString(operationType)).append("\n");
    sb.append("    percentComplete: ").append(toIndentedString(percentComplete)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
