/*
 * Laserfiche Repository API
 * Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>51c16645afa5983c3eb4a849158d6f1e355d2bb0_.20220512.1</p>
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.laserfiche.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * GetDynamicFieldLogicValueRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-16T11:14:25.016422500-04:00[America/New_York]")
public class GetDynamicFieldLogicValueRequest {
  @SerializedName("templateId")
  private Integer templateId = null;

  @SerializedName("fieldValues")
  private Map<String, String> fieldValues = null;

  public GetDynamicFieldLogicValueRequest templateId(Integer templateId) {
    this.templateId = templateId;
    return this;
  }

   /**
   * The template id.
   * @return templateId
  **/
  @Schema(description = "The template id.")
  public Integer getTemplateId() {
    return templateId;
  }

  public void setTemplateId(Integer templateId) {
    this.templateId = templateId;
  }

  public GetDynamicFieldLogicValueRequest fieldValues(Map<String, String> fieldValues) {
    this.fieldValues = fieldValues;
    return this;
  }

  public GetDynamicFieldLogicValueRequest putFieldValuesItem(String key, String fieldValuesItem) {
    if (this.fieldValues == null) {
      this.fieldValues = new HashMap<String, String>();
    }
    this.fieldValues.put(key, fieldValuesItem);
    return this;
  }

   /**
   * The dynamic fields.
   * @return fieldValues
  **/
  @Schema(description = "The dynamic fields.")
  public Map<String, String> getFieldValues() {
    return fieldValues;
  }

  public void setFieldValues(Map<String, String> fieldValues) {
    this.fieldValues = fieldValues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDynamicFieldLogicValueRequest getDynamicFieldLogicValueRequest = (GetDynamicFieldLogicValueRequest) o;
    return Objects.equals(this.templateId, getDynamicFieldLogicValueRequest.templateId) &&
        Objects.equals(this.fieldValues, getDynamicFieldLogicValueRequest.fieldValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateId, fieldValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDynamicFieldLogicValueRequest {\n");
    
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    fieldValues: ").append(toIndentedString(fieldValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
