/*
 * Laserfiche Repository API
 * Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>51c16645afa5983c3eb4a849158d6f1e355d2bb0_.20220512.1</p>
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.laserfiche.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * GetEntryChildren
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-16T11:14:25.016422500-04:00[America/New_York]")
public class GetEntryChildren {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("parentId")
  private Integer parentId = null;

  @SerializedName("fullPath")
  private String fullPath = null;

  @SerializedName("folderPath")
  private String folderPath = null;

  @SerializedName("creator")
  private String creator = null;

  @SerializedName("creationTime")
  private OffsetDateTime creationTime = null;

  @SerializedName("lastModifiedTime")
  private OffsetDateTime lastModifiedTime = null;

  @SerializedName("entryType")
  private OneOfGetEntryChildrenEntryType entryType = null;

  @SerializedName("isContainer")
  private Boolean isContainer = null;

  @SerializedName("isLeaf")
  private Boolean isLeaf = null;

  @SerializedName("templateName")
  private String templateName = null;

  @SerializedName("templateId")
  private Integer templateId = null;

  @SerializedName("volumeName")
  private String volumeName = null;

  @SerializedName("rowNumber")
  private Integer rowNumber = null;

  public GetEntryChildren id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the entry.
   * @return id
  **/
  @Schema(description = "The ID of the entry.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public GetEntryChildren name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the entry.
   * @return name
  **/
  @Schema(description = "The name of the entry.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GetEntryChildren parentId(Integer parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * The ID of the parent entry.
   * @return parentId
  **/
  @Schema(description = "The ID of the parent entry.")
  public Integer getParentId() {
    return parentId;
  }

  public void setParentId(Integer parentId) {
    this.parentId = parentId;
  }

  public GetEntryChildren fullPath(String fullPath) {
    this.fullPath = fullPath;
    return this;
  }

   /**
   * The full path in the Laserfiche repository to the entry.
   * @return fullPath
  **/
  @Schema(description = "The full path in the Laserfiche repository to the entry.")
  public String getFullPath() {
    return fullPath;
  }

  public void setFullPath(String fullPath) {
    this.fullPath = fullPath;
  }

  public GetEntryChildren folderPath(String folderPath) {
    this.folderPath = folderPath;
    return this;
  }

   /**
   * The path in the Laserfiche repository to the parent folder.
   * @return folderPath
  **/
  @Schema(description = "The path in the Laserfiche repository to the parent folder.")
  public String getFolderPath() {
    return folderPath;
  }

  public void setFolderPath(String folderPath) {
    this.folderPath = folderPath;
  }

  public GetEntryChildren creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * The name of the user that created this entry.
   * @return creator
  **/
  @Schema(description = "The name of the user that created this entry.")
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public GetEntryChildren creationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * The creation time of the entry.
   * @return creationTime
  **/
  @Schema(description = "The creation time of the entry.")
  public OffsetDateTime getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(OffsetDateTime creationTime) {
    this.creationTime = creationTime;
  }

  public GetEntryChildren lastModifiedTime(OffsetDateTime lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
    return this;
  }

   /**
   * The last modification time of the entry.
   * @return lastModifiedTime
  **/
  @Schema(description = "The last modification time of the entry.")
  public OffsetDateTime getLastModifiedTime() {
    return lastModifiedTime;
  }

  public void setLastModifiedTime(OffsetDateTime lastModifiedTime) {
    this.lastModifiedTime = lastModifiedTime;
  }

  public GetEntryChildren entryType(OneOfGetEntryChildrenEntryType entryType) {
    this.entryType = entryType;
    return this;
  }

   /**
   * The type of the entry.
   * @return entryType
  **/
  @Schema(description = "The type of the entry.")
  public OneOfGetEntryChildrenEntryType getEntryType() {
    return entryType;
  }

  public void setEntryType(OneOfGetEntryChildrenEntryType entryType) {
    this.entryType = entryType;
  }

   /**
   * A boolean indicating if this entry is a container object; it can have other entries as children.
   * @return isContainer
  **/
  @Schema(description = "A boolean indicating if this entry is a container object; it can have other entries as children.")
  public Boolean isIsContainer() {
    return isContainer;
  }

   /**
   * A boolean indicating if this entry is a leaf object; it cannot have other entries as children.
   * @return isLeaf
  **/
  @Schema(description = "A boolean indicating if this entry is a leaf object; it cannot have other entries as children.")
  public Boolean isIsLeaf() {
    return isLeaf;
  }

  public GetEntryChildren templateName(String templateName) {
    this.templateName = templateName;
    return this;
  }

   /**
   * The name of the template assigned to this entry.
   * @return templateName
  **/
  @Schema(description = "The name of the template assigned to this entry.")
  public String getTemplateName() {
    return templateName;
  }

  public void setTemplateName(String templateName) {
    this.templateName = templateName;
  }

  public GetEntryChildren templateId(Integer templateId) {
    this.templateId = templateId;
    return this;
  }

   /**
   * The id of the template assigned to this entry.
   * @return templateId
  **/
  @Schema(description = "The id of the template assigned to this entry.")
  public Integer getTemplateId() {
    return templateId;
  }

  public void setTemplateId(Integer templateId) {
    this.templateId = templateId;
  }

  public GetEntryChildren volumeName(String volumeName) {
    this.volumeName = volumeName;
    return this;
  }

   /**
   * The name of the volume that this entry is associated with.
   * @return volumeName
  **/
  @Schema(description = "The name of the volume that this entry is associated with.")
  public String getVolumeName() {
    return volumeName;
  }

  public void setVolumeName(String volumeName) {
    this.volumeName = volumeName;
  }

  public GetEntryChildren rowNumber(Integer rowNumber) {
    this.rowNumber = rowNumber;
    return this;
  }

   /**
   * Row number assigned to this entry in the listing.
   * @return rowNumber
  **/
  @Schema(description = "Row number assigned to this entry in the listing.")
  public Integer getRowNumber() {
    return rowNumber;
  }

  public void setRowNumber(Integer rowNumber) {
    this.rowNumber = rowNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetEntryChildren getEntryChildren = (GetEntryChildren) o;
    return Objects.equals(this.id, getEntryChildren.id) &&
        Objects.equals(this.name, getEntryChildren.name) &&
        Objects.equals(this.parentId, getEntryChildren.parentId) &&
        Objects.equals(this.fullPath, getEntryChildren.fullPath) &&
        Objects.equals(this.folderPath, getEntryChildren.folderPath) &&
        Objects.equals(this.creator, getEntryChildren.creator) &&
        Objects.equals(this.creationTime, getEntryChildren.creationTime) &&
        Objects.equals(this.lastModifiedTime, getEntryChildren.lastModifiedTime) &&
        Objects.equals(this.entryType, getEntryChildren.entryType) &&
        Objects.equals(this.isContainer, getEntryChildren.isContainer) &&
        Objects.equals(this.isLeaf, getEntryChildren.isLeaf) &&
        Objects.equals(this.templateName, getEntryChildren.templateName) &&
        Objects.equals(this.templateId, getEntryChildren.templateId) &&
        Objects.equals(this.volumeName, getEntryChildren.volumeName) &&
        Objects.equals(this.rowNumber, getEntryChildren.rowNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, parentId, fullPath, folderPath, creator, creationTime, lastModifiedTime, entryType, isContainer, isLeaf, templateName, templateId, volumeName, rowNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetEntryChildren {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    fullPath: ").append(toIndentedString(fullPath)).append("\n");
    sb.append("    folderPath: ").append(toIndentedString(folderPath)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    lastModifiedTime: ").append(toIndentedString(lastModifiedTime)).append("\n");
    sb.append("    entryType: ").append(toIndentedString(entryType)).append("\n");
    sb.append("    isContainer: ").append(toIndentedString(isContainer)).append("\n");
    sb.append("    isLeaf: ").append(toIndentedString(isLeaf)).append("\n");
    sb.append("    templateName: ").append(toIndentedString(templateName)).append("\n");
    sb.append("    templateId: ").append(toIndentedString(templateId)).append("\n");
    sb.append("    volumeName: ").append(toIndentedString(volumeName)).append("\n");
    sb.append("    rowNumber: ").append(toIndentedString(rowNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
