/*
 * Laserfiche Repository API
 * Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>51c16645afa5983c3eb4a849158d6f1e355d2bb0_.20220512.1</p>
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.laserfiche.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RepositoryInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-16T11:14:25.016422500-04:00[America/New_York]")
public class RepositoryInfo {
  @SerializedName("repoId")
  private String repoId = null;

  @SerializedName("repoName")
  private String repoName = null;

  @SerializedName("webclientUrl")
  private String webclientUrl = null;

  public RepositoryInfo repoId(String repoId) {
    this.repoId = repoId;
    return this;
  }

   /**
   * The repository id.
   * @return repoId
  **/
  @Schema(description = "The repository id.")
  public String getRepoId() {
    return repoId;
  }

  public void setRepoId(String repoId) {
    this.repoId = repoId;
  }

  public RepositoryInfo repoName(String repoName) {
    this.repoName = repoName;
    return this;
  }

   /**
   * The repository name.
   * @return repoName
  **/
  @Schema(description = "The repository name.")
  public String getRepoName() {
    return repoName;
  }

  public void setRepoName(String repoName) {
    this.repoName = repoName;
  }

  public RepositoryInfo webclientUrl(String webclientUrl) {
    this.webclientUrl = webclientUrl;
    return this;
  }

   /**
   * The corresponding repository WebClient url.
   * @return webclientUrl
  **/
  @Schema(description = "The corresponding repository WebClient url.")
  public String getWebclientUrl() {
    return webclientUrl;
  }

  public void setWebclientUrl(String webclientUrl) {
    this.webclientUrl = webclientUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositoryInfo repositoryInfo = (RepositoryInfo) o;
    return Objects.equals(this.repoId, repositoryInfo.repoId) &&
        Objects.equals(this.repoName, repositoryInfo.repoName) &&
        Objects.equals(this.webclientUrl, repositoryInfo.webclientUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(repoId, repoName, webclientUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositoryInfo {\n");
    
    sb.append("    repoId: ").append(toIndentedString(repoId)).append("\n");
    sb.append("    repoName: ").append(toIndentedString(repoName)).append("\n");
    sb.append("    webclientUrl: ").append(toIndentedString(webclientUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
