/*
 * Laserfiche Repository API
 * Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>51c16645afa5983c3eb4a849158d6f1e355d2bb0_.20220512.1</p>
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.laserfiche.api.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ValueToUpdate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-05-16T11:14:25.016422500-04:00[America/New_York]")
public class ValueToUpdate {
  @SerializedName("value")
  private String value = null;

  @SerializedName("position")
  private Integer position = null;

  public ValueToUpdate value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The value assigned to the field at the position specified.
   * @return value
  **/
  @Schema(description = "The value assigned to the field at the position specified.")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public ValueToUpdate position(Integer position) {
    this.position = position;
    return this;
  }

   /**
   * The position of the value in the field. This is 1-indexed for multi value field. It will be ignored for single value field.
   * @return position
  **/
  @Schema(description = "The position of the value in the field. This is 1-indexed for multi value field. It will be ignored for single value field.")
  public Integer getPosition() {
    return position;
  }

  public void setPosition(Integer position) {
    this.position = position;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValueToUpdate valueToUpdate = (ValueToUpdate) o;
    return Objects.equals(this.value, valueToUpdate.value) &&
        Objects.equals(this.position, valueToUpdate.position);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, position);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValueToUpdate {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
