/*
 * Laserfiche Repository API
 * Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>51c16645afa5983c3eb4a849158d6f1e355d2bb0_.20220512.1</p>
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.laserfiche.api.client.test;

import com.laserfiche.api.client.apiserver.AuditReasonsApi;
import com.laserfiche.api.client.model.AuditReasons;
import com.laserfiche.api.client.model.ProblemDetails;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AuditReasonsApi
 */
@Ignore
public class AuditReasonsApiTest {

    private final AuditReasonsApi api = new AuditReasonsApi();

    /**
     * Get the audit reasons associated with the authenticated user.
     *
     * - Returns the audit reasons associated with the authenticated user. Inherited audit reasons are included. - Only includes audit reasons associated with available API functionalities, like delete entry and export document. - If the authenticated user does not have the appropriate Laserfiche feature right, the audit reasons associated with that feature right will not be included.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAuditReasonsTest() throws Exception {
        String repoId = null;
        AuditReasons response = api.getAuditReasons(repoId);

        // TODO: test validations
    }
}
