/*
 * Laserfiche Repository API
 * Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>51c16645afa5983c3eb4a849158d6f1e355d2bb0_.20220512.1</p>
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.laserfiche.api.client.test;

import com.laserfiche.api.client.apiserver.RepositoriesApi;
import com.laserfiche.api.client.model.ProblemDetails;
import com.laserfiche.api.client.model.RepositoryInfo;
import com.laserfiche.api.client.ApiClient;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for RepositoriesApi
 */
@Ignore
public class RepositoriesApiTest {

    private final RepositoriesApi api = new RepositoriesApi();

    /**
     * 
     *
     * - Get the repository resource list that current user has access to.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRepositoryListTest() throws Exception {
        List<RepositoryInfo> response = api.getRepositoryList();

        // TODO: test validations
    }
}
