name: lf-api-client-core-java-CI

on:
  push:
    branches: [ '\d+.x' ]
  pull_request:
    branches: [ '\d+.x' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION_PREFIX: 1.0.0

jobs:
  build-n-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true --file pom.xml

    - name: Run tests
      env:
        ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
        SERVICE_PRINCIPAL_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
        REPOSITORY_ID:  ${{ secrets.DEV_CA_PUBLIC_USE_REPOSITORY_ID_1 }}
      run: mvn test

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "target/surefire-reports/*.xml"

  build-documentation:

    runs-on: ubuntu-latest
    needs: [ build-n-test ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Create temporary directory
      run: mkdir -p ./docs_temp/${{ github.ref_name }}

    - name: Generate Javadoc
      run: mvn javadoc:javadoc

    - name: Move javadoc files to temporary directory
      run: mv ${{ github.workspace }}/target/site/ ${{ github.workspace }}/docs_temp/${{ github.ref_name }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: documentation-artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/docs_temp/${{ github.ref_name }}

    - name: Delete temporary directory
      run: rm -r ./docs_temp

  publish-documentation:

    runs-on: ubuntu-latest
    environment: documentation
    if: ${{ github.run_attempt != 1 }}
    needs: [ build-n-test, build-documentation ] # wait for build to finish

    steps:
      - name: Create temporary directory
        run: mkdir -p ./docs_temp/${{ github.ref_name }}/html/

      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: documentation-artifact
          path: ${{ github.workspace }}/docs_temp/${{ github.ref_name }}/html/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Use your bucket region here

      - name: Upload docs to S3 bucket
        run: aws s3 sync ./docs_temp/${{ github.ref_name }}/html/ s3://apiserver-publish-client-library-docs/${{ github.event.repository.name }}/docs/${{ github.ref_name }} --delete

      - name: Delete temporary directory
        run: rm -r ./docs_temp/${{ github.ref_name }}/html/




