name: veracode-scan

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build project
      run: mvn -B package -Dmaven.test.skip=true --file pom.xml

    - name: Veracode static application security testing (SAST)
      uses: veracode/veracode-uploadandscan-action@0.2.6
      with:
        appname: 'lf-repository-api-client-java'
        createprofile: true
        filepath: 'target'
        vid: '${{ secrets.VERACODE_API_ID }}'
        vkey: '${{ secrets.VERACODE_API_KEY }}'

    - name: Run Veracode software composition analysis (SCA)
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      uses: veracode/veracode-sca@v2.1.6
      with:
        create-issues: false
        allow-dirty: true
        recursive: true